on:
  push:
    branches:
    - master

jobs:
  test-ubuntu-runner:
    name: first job
    runs-on: ubuntu-22.04
    steps:
      - run : echo "first step"
      - run : ls
  test:
     runs-on: ubuntu-22.04
     strategy:
       matrix:
         test: [test]
     steps:
       - name: git checkout
         uses : actions/checkout@v3
       - name: check current repo 
         run : ls
       - name: check matrix 
         run : echo $ {{matrix.test}}
  install-dependencies:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.8.x]
    steps:
      - name: git checkout
        uses : actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm i


    
