on:
  push:
    branches:
    - master

jobs:
  my_first_job:
    name: first job
    runs-on: ubuntu-22.04
    steps:
      - run : echo "first step"
      - run : ls
  my_second_job:
     runs-on: ubuntu-22.04
     strategy:
       matrix:
         test: [test]
     steps:
       - name: git checkout
         uses : actions/checkout@v3
         


    
